name: Security

on: [push]

jobs:
  horus:
    name: horus
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Running Horus Security
      run: |
        curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
        horusec start -p ./